version: '2'
services:
  proxy:
    image: proxy
    ports:
    - "8000:80"
  front:
    image: front
    ports:
    - "5000:80"
  back:
    image: back
    ports:
    - "8080:8080"
    depends_on:
    - postgres
  postgres:
    image: postgres:10
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_USER=postgres
     - POSTGRES_DB=postgres


